FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /workspace
COPY pom.xml .
COPY src ./src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /workspace/target/core-0.0.1-SNAPSHOT.jar app.jar
COPY render-entrypoint.sh /app/render-entrypoint.sh

ENV SPRING_PROFILES_ACTIVE=prod-pg
EXPOSE 8080

ENTRYPOINT ["sh", "/app/render-entrypoint.sh"]
